### ISSUE TITLE
CSharpLoader v1.0.0 Breaking change tracker

### ISSUE THREAD

**Issue by lxymahatma** [czastack/B1CSharpLoader#10]
## CSharpModExample
- [ ] Fully move to [B1.Mod.Template](https://github.com/BlackMythWukongMods/B1.Mod.Template)

## CSharpModBase
- [ ] Rename `Common` to `CommonDir`
- [ ] Rename `Utils` to `InputUtils`, move to`CSharpModBase.Utils` namespace
- [ ] Rename `GamePadButtonEvent` to `GamePadButtonEventArgs`
- [ ] Move `GamePadUtils` to `CSharpModBase.Utils` namespace
- [ ] Move `KeyUtils` to `CSharpModBase.Utils` namespace
- [ ] Rename `Log` to `Logger`

## CSharpModManager
- [ ] Rewrite `Ini` class (maybe)
- [ ] Rename `Develop` to `IsDevelopMode`
